{% set name = "mosdef-dihedral-fit" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit/archive/{{ version }}.tar.gz
  sha256: e6c265b5bb2a7ad36ff666998a32db22249a9c6abf225e82de35ff10812d053a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10,<3.12
    - pip
  run:
    - python >=3.10,<3.12
    - vmd-python
    - mosdef-gomc >=1.4.0
    - pytest
    - pytest-cov
    - coverage
    - gsd =3.3.2

test:
  imports:
    - mosdef_dihedral_fit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  summary: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans
    (RB) torsion.
  description: An open-source, transparent, and lightweight Python software package capable of fitting dihedrals with QM calculations for existing forces fields. This software fits the Optimized Potentials for Liquid Simulations (OPLS) style dihedrals, then also analytically converts them to the periodic dihedral and Ryckaert-Bellemans
    (RB) torsion.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit
  dev_url: https://github.com/GOMC-WSU/MoSDeF-dihedral-fit

extra:
  recipe-maintainers:
    - bc118
    - daico007
    - CalCraven
